/**
 * Formatting Equivalency Tests
 *
 * Validates that Phase 5 reports have structural equivalency with Phase 4 reports.
 * Content differences are tolerated; only formatting structure is tested.
 */

import { describe, it, expect, beforeAll } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import {
  compareReports,
  checkRequiredElements,
  extractClasses
} from '../helpers/dom-comparator.js';
import { REQUIRED_ELEMENTS, ReportType } from '../helpers/required-elements.js';
import { normalizeForSnapshot, extractStructuralSkeleton } from '../helpers/snapshot-normalizer.js';

// =============================================================================
// TEST FIXTURES
// =============================================================================

const FIXTURES_DIR = path.join(__dirname, '../fixtures');

interface TestFixtures {
  phase4: {
    owners: string;
    comprehensive: string;
  };
  phase5: {
    owners: string;
    comprehensive: string;
  };
}

let fixtures: TestFixtures;

beforeAll(() => {
  // Load Phase 4 reference HTML (checked into repo)
  const phase4OwnersPath = path.join(FIXTURES_DIR, 'phase4/owners-report.html');
  const phase4ComprehensivePath = path.join(FIXTURES_DIR, 'phase4/comprehensive-report.html');

  // Load Phase 5 generated HTML (generated by generate-test-reports.ts)
  const phase5OwnersPath = path.join(FIXTURES_DIR, 'phase5/owners-report.html');
  const phase5ComprehensivePath = path.join(FIXTURES_DIR, 'phase5/comprehensive-report.html');

  fixtures = {
    phase4: {
      owners: fs.existsSync(phase4OwnersPath)
        ? fs.readFileSync(phase4OwnersPath, 'utf-8')
        : '',
      comprehensive: fs.existsSync(phase4ComprehensivePath)
        ? fs.readFileSync(phase4ComprehensivePath, 'utf-8')
        : '',
    },
    phase5: {
      owners: fs.existsSync(phase5OwnersPath)
        ? fs.readFileSync(phase5OwnersPath, 'utf-8')
        : '',
      comprehensive: fs.existsSync(phase5ComprehensivePath)
        ? fs.readFileSync(phase5ComprehensivePath, 'utf-8')
        : '',
    },
  };

  // Warn if fixtures are missing
  if (!fixtures.phase4.owners) {
    console.warn('⚠️  Phase 4 Owner\'s Report fixture not found');
  }
  if (!fixtures.phase5.owners) {
    console.warn('⚠️  Phase 5 Owner\'s Report fixture not found. Run: npm run generate:test-reports');
  }
});

// =============================================================================
// OWNER'S REPORT TESTS
// =============================================================================

describe('Owner\'s Report Formatting Equivalency', () => {

  describe('Required DOM Elements', () => {
    it('Phase 5 contains all required structural elements', () => {
      if (!fixtures.phase5.owners) {
        throw new Error('Phase 5 Owner\'s Report not found. Run: npm run generate:test-reports');
      }

      const results = checkRequiredElements(fixtures.phase5.owners, 'owners');
      const failures = results.filter(r => !r.passed);

      if (failures.length > 0) {
        const failureMessages = failures.map(f =>
          `  - ${f.selector}: found ${f.found}, need ${f.required} (${f.description})`
        ).join('\n');
        throw new Error(`Missing required elements:\n${failureMessages}`);
      }

      expect(failures).toHaveLength(0);
    });

    it('Phase 5 contains health score section with required children', () => {
      if (!fixtures.phase5.owners) return;

      const results = checkRequiredElements(fixtures.phase5.owners, 'owners');
      const healthScoreResults = results.filter(r =>
        r.selector.includes('health-score') || r.selector.includes('score-')
      );

      healthScoreResults.forEach(result => {
        expect(result.passed, `${result.description}: ${result.selector}`).toBe(true);
      });
    });

    it('Phase 5 contains chapter score cards', () => {
      if (!fixtures.phase5.owners) return;

      const results = checkRequiredElements(fixtures.phase5.owners, 'owners');
      const chapterResults = results.filter(r =>
        r.selector.includes('chapter') || r.selector.includes('highlight')
      );

      chapterResults.forEach(result => {
        expect(result.passed, `${result.description}: ${result.selector}`).toBe(true);
      });
    });

    it('Phase 5 contains two-column layout', () => {
      if (!fixtures.phase5.owners) return;

      const results = checkRequiredElements(fixtures.phase5.owners, 'owners');
      const layoutResults = results.filter(r =>
        r.selector.includes('two-column') ||
        r.selector.includes('grid') ||
        r.selector.includes('strengths') ||
        r.selector.includes('priorities')
      );

      layoutResults.forEach(result => {
        expect(result.passed, `${result.description}: ${result.selector}`).toBe(true);
      });
    });

    it('Phase 5 uses score band classes', () => {
      if (!fixtures.phase5.owners) return;

      const classes = extractClasses(fixtures.phase5.owners);
      const hasScoreBand =
        classes.has('excellence') ||
        classes.has('proficiency') ||
        classes.has('attention') ||
        classes.has('critical') ||
        classes.has('band-badge') ||
        classes.has('Excellence') ||
        classes.has('Proficiency') ||
        classes.has('Attention') ||
        classes.has('Critical') ||
        [...classes].some(c => c.includes('score-excellence') || c.includes('score-proficiency'));

      expect(hasScoreBand, 'Should have at least one score band class').toBe(true);
    });
  });

  describe('Phase 4 vs Phase 5 Comparison', () => {
    it('Phase 5 has all CSS classes that Phase 4 has', () => {
      if (!fixtures.phase4.owners || !fixtures.phase5.owners) {
        console.warn('Skipping comparison - fixtures not available');
        return;
      }

      const phase4Classes = extractClasses(fixtures.phase4.owners);
      const phase5Classes = extractClasses(fixtures.phase5.owners);

      const missingClasses = [...phase4Classes].filter(c => !phase5Classes.has(c));

      // Allow some variance for dynamically generated classes
      const criticalMissing = missingClasses.filter(c =>
        !c.startsWith('__') && // Skip internal/generated classes
        !c.match(/^[a-z0-9]{6,}$/) // Skip hash-like classes
      );

      if (criticalMissing.length > 0) {
        console.warn('Classes in Phase 4 but not Phase 5:', criticalMissing);
      }

      // This is informational - we don't fail on this
      // The structural tests above are the source of truth
    });

    it('Phase 5 passes structural comparison with Phase 4', () => {
      if (!fixtures.phase4.owners || !fixtures.phase5.owners) {
        console.warn('Skipping comparison - fixtures not available');
        return;
      }

      const comparison = compareReports(
        fixtures.phase4.owners,
        fixtures.phase5.owners,
        'owners'
      );

      if (!comparison.passed) {
        const issues = comparison.missingInPhase5.join('\n  - ');
        throw new Error(`Phase 5 missing required elements:\n  - ${issues}`);
      }

      expect(comparison.passed).toBe(true);
    });
  });
});

// =============================================================================
// COMPREHENSIVE REPORT TESTS
// =============================================================================

describe('Comprehensive Report Formatting Equivalency', () => {

  describe('Required DOM Elements', () => {
    it('Phase 5 contains all required structural elements', () => {
      if (!fixtures.phase5.comprehensive) {
        throw new Error('Phase 5 Comprehensive Report not found. Run: npm run generate:test-reports');
      }

      const results = checkRequiredElements(fixtures.phase5.comprehensive, 'comprehensive');
      const failures = results.filter(r => !r.passed);

      if (failures.length > 0) {
        const failureMessages = failures.map(f =>
          `  - ${f.selector}: found ${f.found}, need ${f.required} (${f.description})`
        ).join('\n');
        throw new Error(`Missing required elements:\n${failureMessages}`);
      }

      expect(failures).toHaveLength(0);
    });

    it('Phase 5 contains cover page', () => {
      if (!fixtures.phase5.comprehensive) return;

      const results = checkRequiredElements(fixtures.phase5.comprehensive, 'comprehensive');
      const coverResult = results.find(r => r.selector.includes('cover-page') || r.selector.includes('report-header'));

      expect(coverResult?.passed, 'Cover page should exist').toBe(true);
    });

    it('Phase 5 contains dimension tables with score badges', () => {
      if (!fixtures.phase5.comprehensive) return;

      const results = checkRequiredElements(fixtures.phase5.comprehensive, 'comprehensive');
      const tableResults = results.filter(r =>
        r.selector.includes('table') || r.selector.includes('badge')
      );

      tableResults.forEach(result => {
        expect(result.passed, `${result.description}: ${result.selector}`).toBe(true);
      });
    });

    it('Phase 5 contains findings grid with category cards', () => {
      if (!fixtures.phase5.comprehensive) return;

      const results = checkRequiredElements(fixtures.phase5.comprehensive, 'comprehensive');
      const findingsResults = results.filter(r =>
        r.selector.includes('findings') || r.selector.includes('insight')
      );

      findingsResults.forEach(result => {
        expect(result.passed, `${result.description}: ${result.selector}`).toBe(true);
      });
    });

    it('Phase 5 contains timeline/roadmap', () => {
      if (!fixtures.phase5.comprehensive) return;

      const results = checkRequiredElements(fixtures.phase5.comprehensive, 'comprehensive');
      const timelineResults = results.filter(r =>
        r.selector.includes('timeline') || r.selector.includes('roadmap') || r.selector.includes('phase')
      );

      timelineResults.forEach(result => {
        expect(result.passed, `${result.description}: ${result.selector}`).toBe(true);
      });
    });

    it('Phase 5 contains financial projections section', () => {
      if (!fixtures.phase5.comprehensive) return;

      const results = checkRequiredElements(fixtures.phase5.comprehensive, 'comprehensive');
      const financialResults = results.filter(r =>
        r.selector.includes('financial')
      );

      financialResults.forEach(result => {
        expect(result.passed, `${result.description}: ${result.selector}`).toBe(true);
      });
    });
  });

  describe('Phase 4 vs Phase 5 Comparison', () => {
    it('Phase 5 passes structural comparison with Phase 4', () => {
      if (!fixtures.phase4.comprehensive || !fixtures.phase5.comprehensive) {
        console.warn('Skipping comparison - fixtures not available');
        return;
      }

      const comparison = compareReports(
        fixtures.phase4.comprehensive,
        fixtures.phase5.comprehensive,
        'comprehensive'
      );

      if (!comparison.passed) {
        const issues = comparison.missingInPhase5.join('\n  - ');
        throw new Error(`Phase 5 missing required elements:\n  - ${issues}`);
      }

      expect(comparison.passed).toBe(true);
    });
  });
});

// =============================================================================
// SNAPSHOT TESTS
// =============================================================================

describe('Formatting Snapshots', () => {

  describe('Owner\'s Report Structure', () => {
    it('structural skeleton matches snapshot', () => {
      if (!fixtures.phase5.owners) {
        console.warn('Skipping snapshot - Phase 5 Owner\'s Report not found');
        return;
      }

      const skeleton = extractStructuralSkeleton(fixtures.phase5.owners);
      expect(skeleton).toMatchSnapshot();
    });

    it('normalized HTML matches snapshot', () => {
      if (!fixtures.phase5.owners) return;

      const normalized = normalizeForSnapshot(fixtures.phase5.owners);
      expect(normalized).toMatchSnapshot();
    });
  });

  describe('Comprehensive Report Structure', () => {
    it('structural skeleton matches snapshot', () => {
      if (!fixtures.phase5.comprehensive) {
        console.warn('Skipping snapshot - Phase 5 Comprehensive Report not found');
        return;
      }

      const skeleton = extractStructuralSkeleton(fixtures.phase5.comprehensive);
      expect(skeleton).toMatchSnapshot();
    });

    it('normalized HTML matches snapshot', () => {
      if (!fixtures.phase5.comprehensive) return;

      const normalized = normalizeForSnapshot(fixtures.phase5.comprehensive);
      expect(normalized).toMatchSnapshot();
    });
  });
});
